name: My CI/CD Pipeline
run-name: My CI/CD


on:
  push:
    branches:
      - main
    # paths-ignore:
    #   - .github/workflows/my_CICD.yml
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: false

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          cd app
          pytest


###############################################
###############################################

# End of demo1

###############################################
###############################################

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t get_users:v3 ./app
          docker tag users_app:v1 rtfm79/get_users:v3

      - name: Push Docker image
        run: docker push rtfm79/get_users:v3



###############################################
###############################################

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Pull Docker image
        run: |
          docker pull rtfm79/get_users:v3

      - name: Docker Run
        run: |
          docker run --rm rtfm79/get_users:v3 > get_users.output.txt
          cat get_users.output.txt

      - name: Upload get_users.output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: get_users_output
          path: get_users.output.txt
